### GET USERS
GET http://localhost:3000/user?size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExOTkzNGFhMjdjYTA5NzYzNTI1MjMiLCJpYXQiOjE2MjEyMzYzMjcsImV4cCI6MTYyMTI1NzkyNywidHlwZSI6ImFjY2VzcyJ9.jqVbdzOuwY4g6ceJzYDNIZH2Sx6DI4JZIz4ohygxRIY

### GET USER
GET http://localhost:3000/user/60a22596aa27ca0976352527
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGEyMjU5NmFhMjdjYTA5NzYzNTI1MjciLCJpYXQiOjE2MjEyMzkxOTAsImV4cCI6MTYyMTI2MDc5MCwidHlwZSI6ImFjY2VzcyJ9.k_nWasKtLtOzqf9bm9jrYR4CqViR-khcLJCgEU8EkpA





### UPDATE USER
PATCH http://localhost:3000/user/60a19934aa27ca0976352523
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExOTkzNGFhMjdjYTA5NzYzNTI1MjMiLCJpYXQiOjE2MjEyMzYzMjcsImV4cCI6MTYyMTI1NzkyNywidHlwZSI6ImFjY2VzcyJ9.jqVbdzOuwY4g6ceJzYDNIZH2Sx6DI4JZIz4ohygxRIY

&name=Talat
&gender=male
&country=USA


### UPDATE USER
PATCH http://localhost:3000/user/60a22596aa27ca0976352527
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGEyMjU5NmFhMjdjYTA5NzYzNTI1MjciLCJpYXQiOjE2MjEyMzkxOTAsImV4cCI6MTYyMTI2MDc5MCwidHlwZSI6ImFjY2VzcyJ9.k_nWasKtLtOzqf9bm9jrYR4CqViR-khcLJCgEU8EkpA

&name=Selda
&gender=female
&country=TUR






### DELETE USER
DELETE http://localhost:3000/user/60a22596aa27ca0976352527
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGEyMjU5NmFhMjdjYTA5NzYzNTI1MjciLCJpYXQiOjE2MjEyMzkxOTAsImV4cCI6MTYyMTI2MDc5MCwidHlwZSI6ImFjY2VzcyJ9.k_nWasKtLtOzqf9bm9jrYR4CqViR-khcLJCgEU8EkpA


### ADD USER
POST http://localhost:3000/user/
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGEyMjU5NmFhMjdjYTA5NzYzNTI1MjciLCJpYXQiOjE2MjEyMzkxOTAsImV4cCI6MTYyMTI2MDc5MCwidHlwZSI6ImFjY2VzcyJ9.k_nWasKtLtOzqf9bm9jrYR4CqViR-khcLJCgEU8EkpA

&id=60a22596aa27ca0976352527
&email=user1@gmail.com
&role=user
&name=Talha
&gender=male
&country=TUR






### CHANGE USER ROLE
PUT http://localhost:3000/user/60a22596aa27ca0976352527/role
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExOTkzNGFhMjdjYTA5NzYzNTI1MjMiLCJpYXQiOjE2MjEyMzYzMjcsImV4cCI6MTYyMTI1NzkyNywidHlwZSI6ImFjY2VzcyJ9.jqVbdzOuwY4g6ceJzYDNIZH2Sx6DI4JZIz4ohygxRIY

&role=user