### Hello
GET http://localhost:3000/

### insert talatkuyuk@gmail.com
GET http://localhost:3000/t1

### Not Found Request
GET http://localhost:3000/comments


### LOGIN SUCCESS
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

&email=user1@gmail.com
&password=12345678


### LOGIN FAILED
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

&email=user5@gmail.com
&password=Tk3231tK.


### REGISTER SUCCESS
POST http://localhost:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

&email=talat@gmail.com
&password=Tk3231tK.
&passwordConfirmation=Tk3231tK.

### LOGOUT
POST http://localhost:3000/auth/logout
Content-Type: application/x-www-form-urlencoded

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDg5YWFmMzFhMTI1YmVkZGRjMTFhNTgiLCJpYXQiOjE2MTk2MzQ5MzEsImV4cCI6MTYyMjIyNjkzMSwidHlwZSI6InJlZnJlc2gifQ.FUHFFk58TkUQG80sHOeyTqcOJQcMHTSZl2KXq-OZJE4

### SIGNOUT
POST http://localhost:3000/auth/signout
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhiMmY2OTFhNjEwMzZiMGQwYjZjZDMiLCJpYXQiOjE2MTk3MzQzNzcsImV4cCI6MTYxOTc0MTU3NywidHlwZSI6ImFjY2VzcyJ9.dY6T5GrITVrJdU15SkAJYfez_DiPAl46PxzZrSaBuQ8

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhiMmY2OTFhNjEwMzZiMGQwYjZjZDMiLCJpYXQiOjE2MTk3MzQzNzcsImV4cCI6MTYyMjMyNjM3NywidHlwZSI6InJlZnJlc2gifQ.GFPw_B3O1ILfFQtH3BoxyZn9k80uqUte_g-qxsmyuAA

### REFRESH TOKENS
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/x-www-form-urlencoded

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk5NTM4NjMsImV4cCI6MTYyMjU0NTg2MywidHlwZSI6InJlZnJlc2gifQ.rhIgHr002mhUJbrkeMfKWVl4bWSHtC_GJ4RZ40CQtpU

### SEND VERIFICATION EMAIL
POST http://localhost:3000/auth/send-verification-email
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhmZDBkNjY3MmIwODQwM2I5OGM4OTYiLCJpYXQiOjE2MjAwNDE3NDQsImV4cCI6MTYyMDA2MzM0NCwidHlwZSI6ImFjY2VzcyJ9.h7xkyqrwmtgJblUYSisY9o_oCcip5ijTd6LVKL6ejng

### VERIFY EMAIL
POST http://localhost:3000/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk3MzUxNjUsImV4cCI6MTYxOTk1MTE2NSwidHlwZSI6InZlcmlmeUVtYWlsIn0.7JUPOp5L_12Pq2785TJXRnSuu-JmbsPvvFQvlPpsHi8


### FORGOT PASSWORD (SEND EMAIL RESET TOKEN)
POST http://localhost:3000/auth/forgot-password
Content-Type: application/x-www-form-urlencoded

&email=talatkuyuk@gmail.com

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MjAwNTU2NjcsImV4cCI6MTYyMDA1OTI2NywidHlwZSI6InJlc2V0UGFzc3dvcmQifQ.ODWFaXlAd17DHn4PUkLKdiC6SPSdwm2iTxN5iDa_mVY
Content-Type: application/x-www-form-urlencoded

&password=Tk3231tK.


### CHANGE PASSWORD
POST http://localhost:3000/auth/change-password
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhmZDBkNjY3MmIwODQwM2I5OGM4OTYiLCJpYXQiOjE2MjAwNDE3NDQsImV4cCI6MTYyMDA2MzM0NCwidHlwZSI6ImFjY2VzcyJ9.h7xkyqrwmtgJblUYSisY9o_oCcip5ijTd6LVKL6ejng

&currentPassword=Tk3231tK.
&password=Tk3231tK.
&passwordConfirmation=Tk3231tK.

### TOKENS
{
  "user": {
    "email": "talat@gmail.com",
    "isEmailVerified": false,
    "id": "60901c8fe76cfa5315bff290",
    "isAuthorized": true
  },
  "tokens": {
    "access": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWM4ZmU3NmNmYTUzMTViZmYyOTAiLCJpYXQiOjE2MjAwNTcyMzEsImV4cCI6MTYyMDA3ODgzMSwidHlwZSI6ImFjY2VzcyJ9.H41WGElw49uKRpHfdMla2GsMDxNC7OgQZhCMsyOYz_g",
      "expires": "2021-05-03T21:53:51.959Z"
    },
    "refresh": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWM4ZmU3NmNmYTUzMTViZmYyOTAiLCJpYXQiOjE2MjAwNTcyMzEsImV4cCI6MTYyMjY0OTIzMSwidHlwZSI6InJlZnJlc2gifQ.MymdgRrkV47IHZZvX-v25galJGyKtQUBCmTmGnvBPuY",
      "expires": "2021-06-02T15:53:51.962Z"
    }
  }
}

{
  "user": {
    "email": "user1@gmail.com",
    "isEmailVerified": false,
    "id": "60901f95bfd7e653b8c9e8c2",
    "isAuthorized": true
  },
  "tokens": {
    "access": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWY5NWJmZDdlNjUzYjhjOWU4YzIiLCJpYXQiOjE2MjAwNTgzNTksImV4cCI6MTYyMDA3OTk1OSwidHlwZSI6ImFjY2VzcyJ9.bjbSQg9AxdUReX-4eh1TkihrWr9PTRFy730zIZRjT3w",
      "expires": "2021-05-03T22:12:39.939Z"
    },
    "refresh": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWY5NWJmZDdlNjUzYjhjOWU4YzIiLCJpYXQiOjE2MjAwNTgzNTksImV4cCI6MTYyMjY1MDM1OSwidHlwZSI6InJlZnJlc2gifQ.Z_gcKxoBR6B7fpC_uSSF9XeXRl_n3PF_zve38Bf6PmQ",
      "expires": "2021-06-02T16:12:39.941Z"
    }
  }
}
