### Hello
GET http://localhost:3000/

### Status
GET http://localhost:3000/status

### Not Found Request
GET http://localhost:3000/comments




### REGISTER
POST http://localhost:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

&email=talatkuyuk@gmail.com
&password=Tk3231tK.
&passwordConfirmation=Tk3231tK.

### ADD USER(SELF) AFTER REGISTRATION
POST http://localhost:3000/user
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTAyYTVmN2FjN2M2YzIwZmYwMWVkYTciLCJpYXQiOjE2Mjc1NjM1MTEsImV4cCI6MTYyNzU4NTExMSwianRpIjoiMjBhMWZhOWJlZDliNmVjZmFhNDBiODk2OGU3ODM5YWUiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyJ9.lVKmx0Zy19awHe568m5z8v6HaRNMiCu-mjHyB_AUTBk

&id=6102a5f7ac7c6c20ff01eda7
&email=talatkuyuk@gmail.com
&role=user
&gender=male




### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

&email=talatkuyuk@gmail.com
&password=Tk3231tK.

### LOGOUT
POST http://localhost:3000/auth/logout
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGZmMmQ3OGY4YWViMDA0M2U0N2Q2Y2YiLCJpYXQiOjE2MjczMzYwNTYsImV4cCI6MTYyNzM1NzY1NiwianRpIjoiMTIyMWMzYjY0ODI5NWNiZjhkZmEwNzcxZTZkNjI2YTUiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyJ9.340Qai3MLa76GeZ-qC3sYIgsQLRLBEwRdtibUs1M2cA

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGZmMmQ3OGY4YWViMDA0M2U0N2Q2Y2YiLCJpYXQiOjE2MjczMzYwNTYsImV4cCI6MTYyOTkyODA1NiwianRpIjoiNjBhZWRkZTljZmMzMGU2NDk0ZjJlNWUzNzQyNjNmNjYiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6InJlZnJlc2gifQ.VMDf5zbr6iki0Quq9w6X0d7ZIAIZhlO0pbnOuTFlF3s




### DELETE USER(SELF) BEFORE SIGNOUT
DELETE http://localhost:3000/user/60a19934aa27ca0976352523
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGZmMmQ3OGY4YWViMDA0M2U0N2Q2Y2YiLCJpYXQiOjE2MjczMzg5ODIsImV4cCI6MTYyNzM2MDU4MiwianRpIjoiZTFmN2UzMWJiMmY3NTk3NzM0ZjNmZjA1M2ZlZmQxMGEiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyJ9.TDeF_EW6gRWGFc0uP-KMr823SRhrr3lAavPVwdxKKKo

### SIGNOUT
POST http://localhost:3000/auth/signout
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTExYWIwOTY0OTM2MTQxZDE4MDRlZmYiLCJpYXQiOjE2Mjg1OTkyMTIsImV4cCI6MTYyODYyMDgxMiwianRpIjoiYzdmOWZlMDU1ZTJlZjk2YzM2OGFhMWJmOGYxOTc0ODUiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyIsIm5iZiI6MTYyODU5OTIxMn0.K0h057xKZyKdS2IdenpdUuFRqtP8T7vUd12P6Obdf3I

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTExYWIwOTY0OTM2MTQxZDE4MDRlZmYiLCJpYXQiOjE2Mjg1OTkyMTIsImV4cCI6MTYzMTE5MTIxMiwianRpIjoiYzdmOWZlMDU1ZTJlZjk2YzM2OGFhMWJmOGYxOTc0ODUiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6InJlZnJlc2giLCJuYmYiOjE2Mjg1OTk1MTJ9.m4tYf11v1Cc0ajnxD8wSTS1536A9-GZZF9I9cVrjlLA




### REFRESH TOKENS
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/x-www-form-urlencoded

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTEyYzUzYThlMzdhYTQ4MDcwNzA3NDQiLCJpYXQiOjE2Mjg2MjAwOTAsImV4cCI6MTYzMTIxMjA5MCwianRpIjoiMjgyZTYxNmQ0ZjAxYjQ2YmUxN2RlYTBiZmI2MWU1NGQiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6InJlZnJlc2giLCJuYmYiOjE2Mjg2MjAzOTB9.VgYFAK8RgcVpq73H-B1fJGSf1x9gBIA-PEDZ07PR_9Q




### SEND VERIFICATION EMAIL
POST http://localhost:3000/auth/send-verification-email
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGZmMmQ3OGY4YWViMDA0M2U0N2Q2Y2YiLCJpYXQiOjE2MjczMzYwNTYsImV4cCI6MTYyNzM1NzY1NiwianRpIjoiMTIyMWMzYjY0ODI5NWNiZjhkZmEwNzcxZTZkNjI2YTUiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyJ9.340Qai3MLa76GeZ-qC3sYIgsQLRLBEwRdtibUs1M2cA

### VERIFY EMAIL
POST http://localhost:3000/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExMmNlNTk0NDdkYjczMGFjNWI2NmEiLCJpYXQiOjE2MjExOTQwMzEsImV4cCI6MTYyMTQxMDAzMSwidHlwZSI6InZlcmlmeUVtYWlsIn0.BQHeuyv_d6P1FG8cXMSv30uvKGXEyxDnDWoTRzyw4bw




### FORGOT PASSWORD (SEND EMAIL FOR PASSWORD RESET TOKEN)
POST http://localhost:3000/auth/forgot-password
Content-Type: application/x-www-form-urlencoded

&email=talatkuyuk@gmail.com

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGExOTkzNGFhMjdjYTA5NzYzNTI1MjMiLCJpYXQiOjE2MjEzMTkyODUsImV4cCI6MTYyMTMyMjg4NSwidHlwZSI6InJlc2V0UGFzc3dvcmQifQ.C0h8JJDn3GFm0ZgUUKC0AdJtwyHl8zDHD2XYLobsQLc
Content-Type: application/x-www-form-urlencoded

&password=Tk3231tK.





### TOKENS

{
  "user": {
    "email": "talatkuyuk@gmail.com",
    "isEmailVerified": false,
    "createdAt": 1628620090823,
    "id": "6112c53a8e37aa4807070744"
  },
  "tokens": {
    "access": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTEyYzUzYThlMzdhYTQ4MDcwNzA3NDQiLCJpYXQiOjE2Mjg2MjAwOTAsImV4cCI6MTYyODY0MTY5MCwianRpIjoiMjgyZTYxNmQ0ZjAxYjQ2YmUxN2RlYTBiZmI2MWU1NGQiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6ImFjY2VzcyIsIm5iZiI6MTYyODYyMDA5MH0.4k4vFfJ6EBPDSxmnnqNtj3r8fCw9fWjzCJyOnHyc3U8",
      "expires": "2021-08-11T00:28:10.928Z"
    },
    "refresh": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTEyYzUzYThlMzdhYTQ4MDcwNzA3NDQiLCJpYXQiOjE2Mjg2MjAwOTAsImV4cCI6MTYzMTIxMjA5MCwianRpIjoiMjgyZTYxNmQ0ZjAxYjQ2YmUxN2RlYTBiZmI2MWU1NGQiLCJ1YSI6InZzY29kZS1yZXN0Y2xpZW50IiwidHlwZSI6InJlZnJlc2giLCJuYmYiOjE2Mjg2MjAzOTB9.VgYFAK8RgcVpq73H-B1fJGSf1x9gBIA-PEDZ07PR_9Q",
      "expires": "2021-09-09T18:28:10.928Z"
    }
  }
}