### Hello
GET http://localhost:3000/

### insert talatkuyuk@gmail.com
GET http://localhost:3000/t1

### Not Found Request
GET http://localhost:3000/comments


### LOGIN SUCCESS
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

&email=user1@gmail.com
&password=12345678


### LOGIN FAILED
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

&email=user5@gmail.com
&password=Tk3231tK.


### REGISTER SUCCESS
POST http://localhost:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

&email=user1@gmail.com
&password=Tk3231tK.
&passwordConfirmation=Tk3231tK.

### LOGOUT
POST http://localhost:3000/auth/logout
Content-Type: application/x-www-form-urlencoded

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDg5YWFmMzFhMTI1YmVkZGRjMTFhNTgiLCJpYXQiOjE2MTk2MzQ5MzEsImV4cCI6MTYyMjIyNjkzMSwidHlwZSI6InJlZnJlc2gifQ.FUHFFk58TkUQG80sHOeyTqcOJQcMHTSZl2KXq-OZJE4

### SIGNOUT
POST http://localhost:3000/auth/signout
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWM4ZmU3NmNmYTUzMTViZmYyOTAiLCJpYXQiOjE2MjAwNTcyMzEsImV4cCI6MTYyMDA3ODgzMSwidHlwZSI6ImFjY2VzcyJ9.H41WGElw49uKRpHfdMla2GsMDxNC7OgQZhCMsyOYz_g

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwMWM4ZmU3NmNmYTUzMTViZmYyOTAiLCJpYXQiOjE2MjAwNTcyMzEsImV4cCI6MTYyMjY0OTIzMSwidHlwZSI6InJlZnJlc2gifQ.MymdgRrkV47IHZZvX-v25galJGyKtQUBCmTmGnvBPuY

### REFRESH TOKENS
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/x-www-form-urlencoded

&refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk5NTM4NjMsImV4cCI6MTYyMjU0NTg2MywidHlwZSI6InJlZnJlc2gifQ.rhIgHr002mhUJbrkeMfKWVl4bWSHtC_GJ4RZ40CQtpU

### SEND VERIFICATION EMAIL
POST http://localhost:3000/auth/send-verification-email
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhmZDBkNjY3MmIwODQwM2I5OGM4OTYiLCJpYXQiOjE2MjAwNDE3NDQsImV4cCI6MTYyMDA2MzM0NCwidHlwZSI6ImFjY2VzcyJ9.h7xkyqrwmtgJblUYSisY9o_oCcip5ijTd6LVKL6ejng

### VERIFY EMAIL
POST http://localhost:3000/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk3MzUxNjUsImV4cCI6MTYxOTk1MTE2NSwidHlwZSI6InZlcmlmeUVtYWlsIn0.7JUPOp5L_12Pq2785TJXRnSuu-JmbsPvvFQvlPpsHi8


### FORGOT PASSWORD (SEND EMAIL RESET TOKEN)
POST http://localhost:3000/auth/forgot-password
Content-Type: application/x-www-form-urlencoded

&email=talatkuyuk@gmail.com

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MjAwNTU2NjcsImV4cCI6MTYyMDA1OTI2NywidHlwZSI6InJlc2V0UGFzc3dvcmQifQ.ODWFaXlAd17DHn4PUkLKdiC6SPSdwm2iTxN5iDa_mVY
Content-Type: application/x-www-form-urlencoded

&password=Tk3231tK.


### CHANGE PASSWORD
POST http://localhost:3000/auth/change-password
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhmZDBkNjY3MmIwODQwM2I5OGM4OTYiLCJpYXQiOjE2MjAwNDE3NDQsImV4cCI6MTYyMDA2MzM0NCwidHlwZSI6ImFjY2VzcyJ9.h7xkyqrwmtgJblUYSisY9o_oCcip5ijTd6LVKL6ejng

&currentPassword=Tk3231tK.
&password=Tk3231tK.
&passwordConfirmation=Tk3231tK.

### TOKENS
{
  "user": {
    "email": "talat@gmail.com",
    "isEmailVerified": false,
    "id": "609057f38b7b7659dc0cdef9",
    "isAuthorized": true
  },
  "tokens": {
    "access": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwNTdmMzhiN2I3NjU5ZGMwY2RlZjkiLCJpYXQiOjE2MjAwNzI0MzUsImV4cCI6MTYyMDA5NDAzNSwidHlwZSI6ImFjY2VzcyJ9.ERzxqN8JtNCYFmK6ZHS_Tb1a5tGvgPLDlGcuJjWCBnI",
      "expires": "2021-05-04T02:07:15.429Z"
    },
    "refresh": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwNTdmMzhiN2I3NjU5ZGMwY2RlZjkiLCJpYXQiOjE2MjAwNzI0MzUsImV4cCI6MTYyMjY2NDQzNSwidHlwZSI6InJlZnJlc2gifQ.aWBx7QyuoxwspTcRmORtVUfG3cuqwJje4yL4_pYU_Sc",
      "expires": "2021-06-02T20:07:15.432Z"
    }
  }
}

{
  "user": {
    "email": "user1@gmail.com",
    "isEmailVerified": false,
    "id": "609058268b7b7659dc0cdefb",
    "isAuthorized": true
  },
  "tokens": {
    "access": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwNTgyNjhiN2I3NjU5ZGMwY2RlZmIiLCJpYXQiOjE2MjAwNzI0ODYsImV4cCI6MTYyMDA5NDA4NiwidHlwZSI6ImFjY2VzcyJ9.hVh4aPGF3kzt1l_Hle_LAm0ZrDmNpnUhxnb2_Zvb6-o",
      "expires": "2021-05-04T02:08:06.475Z"
    },
    "refresh": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDkwNTgyNjhiN2I3NjU5ZGMwY2RlZmIiLCJpYXQiOjE2MjAwNzI0ODYsImV4cCI6MTYyMjY2NDQ4NiwidHlwZSI6InJlZnJlc2gifQ.vn_y50kV2v5NZi1gIYMRI_Pc8CwYzKttZHZAGX511Vo",
      "expires": "2021-06-02T20:08:06.475Z"
    }
  }
}
