### GET USER BY ID
GET http://localhost:3000/user/608c6b3315e6e3194be49df3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk4MTUwNDQsImV4cCI6MTYxOTgyMjI0NCwidHlwZSI6ImFjY2VzcyJ9.nzI4R_luIHcMdgeSrg1k1j7oYWIXdje6RTroRyOBrMc

### UPDATE USER BY ID
PATCH http://localhost:3000/user/608a751a975a0a44b018c912
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk3NzUxOTUsImV4cCI6MTYxOTc4MjM5NSwidHlwZSI6ImFjY2VzcyJ9.3uExrrM6a9B-ENrXg_UhHckMOLFAbYqh4AaVAgLfigY

&name=Talat KÜYÜK
&gender=male
&country=TUR


### UPDATE USER BY ID
PATCH http://localhost:3000/user/608b36ef16f66a734e19be9c
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhiMzZlZjE2ZjY2YTczNGUxOWJlOWMiLCJpYXQiOjE2MTk3MzYzMDMsImV4cCI6MTYxOTc0MzUwMywidHlwZSI6ImFjY2VzcyJ9.DSd55anpvFp0j3VFXmXMJL-IE0Ete4Uru37_dqJA5Dk

&name=xx KUYUK
&gender=none
&country=USA


### DELETE USER BY ID
DELETE http://localhost:3000/user/608bdcd456419f0fd452633b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk3NzUxOTUsImV4cCI6MTYxOTc4MjM5NSwidHlwZSI6ImFjY2VzcyJ9.3uExrrM6a9B-ENrXg_UhHckMOLFAbYqh4AaVAgLfigY


### ADD USER
POST http://localhost:3000/user/
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk4MTUwNDQsImV4cCI6MTYxOTgyMjI0NCwidHlwZSI6ImFjY2VzcyJ9.nzI4R_luIHcMdgeSrg1k1j7oYWIXdje6RTroRyOBrMc

&email=user@gmail.com
&password=12345678
&role=user
&name=Talat KÜYÜK
&gender=male
&country=TUR


### TOGGLE USER ABILITY - enable / disable
PUT http://localhost:3000/user/608c6b3315e6e3194be49df3/toggle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk4MTUwNDQsImV4cCI6MTYxOTgyMjI0NCwidHlwZSI6ImFjY2VzcyJ9.nzI4R_luIHcMdgeSrg1k1j7oYWIXdje6RTroRyOBrMc

### CHANGE USER ROLE
PUT http://localhost:3000/user/608c6b3315e6e3194be49df3/role
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDhhNzUxYTk3NWEwYTQ0YjAxOGM5MTIiLCJpYXQiOjE2MTk4MTUwNDQsImV4cCI6MTYxOTgyMjI0NCwidHlwZSI6ImFjY2VzcyJ9.nzI4R_luIHcMdgeSrg1k1j7oYWIXdje6RTroRyOBrMc

&role=user