const express = require("express");
const router = express.Router();

// to bind swagger with express and show the ui
const swaggerUi = require("swagger-ui-express");

// get validated swagger spesification in json format generated by 'swagger-jsdoc'
const { swaggerSpec } = require("../swagger/swaggerSpec");

// Save generated swagger.json file into public directroy
// var fs = require('fs');
// const { Console } = require('console');
// const output = fs.createWriteStream('./src/public/swagger.json');
// const logger = new Console(output);
// logger.log(JSON.stringify(swaggerSpec, null, 4));

const config = require("../config");

const options = {
  explorer: true,
  swaggerOptions: {
    validatorUrl: null,
    oauth2RedirectUrl: "https://localhost:8443/docs/oauth2-redirect.html",
    oauth: {
      clientId: config.google_client_id,
      clientSecret: config.google_client_secret,
      appName: "todo-app",
      realm: "my-realm",
      additionalQueryStringParams: { test: "hello" },
      usePkceWithAuthorizationCodeGrant: false,
    },
  },
  customCss: `
		.topbar-wrapper img { content:url('/logo.png'); width:50px; height:auto; }
		.topbar-wrapper a::after { content: 'Safemeals'; color: #fff; font-size: 20px; font-weight: bold; margin-left: 20px; }
		.swagger-ui .topbar { background-color: #000; border-bottom: 5px solid #5dc6d1; }`,
  customSiteTitle: "Safemeals APIs",
  customfavIcon: "/favicon.ico",
  //customCssUrl: 'https://cdn.jsdelivr.net/npm/swagger-ui-themes@3.0.0/themes/3.x/theme-newspaper.css'
  customJs: "/custom.js",
};

router.use("/", swaggerUi.serve);
router.get("/", swaggerUi.setup(swaggerSpec, options));

module.exports = router;
